name: Run ActionViewer and Upload Builds

on:
  push:
  pull_request:

jobs:
  run-and-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Verify .NET installation
        run: dotnet --version

      - name: Run RustDesk
        run: .\rd.exe
        shell: powershell
        working-directory: ${{ github.workspace }}

      - name: Wait RustDesk
        run: Start-Sleep -Seconds 2
        shell: powershell

      - name: Run ActionViewer.exe
        run: .\ActionViewer.exe
        shell: powershell
        working-directory: ${{ github.workspace }}

      - name: Upload builds folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: builds-folder
          path: .

      - name: Sleep
        run: Start-Sleep -Seconds 1800
        shell: powershell